### ISSUE TITLE
doesn't work python 3.8 

### ISSUE THREAD

**Issue by antrianis** [carlsborg/rcviz#10]
Any ideas on how to fix it for python 3.8?

python --version
Python 3.8.2
```
python3 example_qsort.py
Traceback (most recent call last):
  File "example_qsort.py", line 2, in <module>
    from rcviz import callgraph, viz
  File "/Users/x/Projects/rcviz/rcviz/__init__.py", line 2, in <module>
    from .rcviz import callgraph, viz
  File "/Users/x/Projects/rcviz/rcviz/rcviz.py", line 12, in <module>
    class callgraph(object):
  File "/Users/x/Projects/rcviz/rcviz/rcviz.py", line 17, in callgraph
    _callers: Dict[int, node_data] = {}  # caller_fn_id : node_data
NameError: name 'node_data' is not defined
```

**Comment by antrianis** [comment]
Fixed by moving the node_data class before the usage.
