### ISSUE TITLE
Example code does not work with ipython

### ISSUE THREAD

**Issue by stharding** [carlsborg/rcviz#4]
I'm running OS X 10.11.4, using Anaconda. If I paste your sample code into a python shell, it works fine, but using the %paste magic function in ipython results in the error pasted below. I also tried it in an iPython Notebook--same result.

```
$ ipython
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %paste
from rcviz import callgraph, viz

@viz
def quicksort(items):
    if len(items) <= 1:
        return items
    else:
        pivot = items[0]
        lesser = quicksort([x for x in items[1:] if x < pivot])
        greater = quicksort([x for x in items[1:] if x >= pivot])
        return lesser + [pivot] + greater

print quicksort( list("helloworld") )
callgraph.render("sort.png")

## -- End pasted text --
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-2d0324c766ba> in <module>()
     11         return lesser + [pivot] + greater
     12
---> 13 print quicksort( list("helloworld") )
     14 callgraph.render("sort.png")

/Users/harding/anaconda/lib/python2.7/site-packages/rcviz-0.1-py2.7.egg/rcviz/rcviz.pyc in __call__(self, *args, **kwargs)
    172                 if caller_frame_id:
    173                         edgeinfo = [this_frame_id, callgraph.get_counter()]
--> 174                         g_callers[caller_frame_id].child_methods.append( edgeinfo )
    175                         callgraph.increment()
    176

KeyError: 4329494704

In [2]:
```

**Comment by nirmalthacker** [comment]
Im seeing this too. here's my code that hits the same bug 
```

from rcviz import callgraph, viz
@viz
def rec_printAllSubsets(unselected, selected, n):
	if n < len(unselected):
		rec_printAllSubsets(unselected, selected, n+1)
		rec_printAllSubsets(unselected, selected + " " + str(unselected[n]), n+ 1)
	else:
		print("{" + selected + " }")
		return

def printAllSubsets(l):
	rec_printAllSubsets(l, "", 0)

printAllSubsets([1,2,3])
callgraph.render("subsets.png")
```

```
zeus:python_datastructures nirmal$ python subsets.py
Traceback (most recent call last):
  File "subsets.py", line 17, in <module>
    printAllSubsets([1,2,3])
  File "subsets.py", line 15, in printAllSubsets
    rec_printAllSubsets(l, "", 0)
  File "/usr/local/lib/python2.7/site-packages/rcviz-0.1-py2.7.egg/rcviz/rcviz.py", line 174, in __call__
    g_callers[caller_frame_id].child_methods.append( edgeinfo )
KeyError: 4377665104
```

**Comment by DamnedFacts** [comment]
I've just completed an updated fork of this project to include Python3 Jupyter, and IPython support.
https://github.com/DamnedFacts/rcviz

**Comment by Naereen** [comment]
Thank @DamnedFacts, your fork works perfectly fine for me on IPython 7.16.1 for Python 3.6.9 !

**Comment by carlsborg** [comment]
Really like @DamnedFacts fork, i am humbled that you found this useful :) I've revisited and added this feature with a bigger refactor.
